# This workflow will build a goplus project
name: Go+

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go/Go+
      uses: goplus/setup-goplus@v1
      with:
        go-version: "1.18"
        gop-version: "main"

    - name: SingleFile Mode Test
      run: |
        gop build ./...

    - name: Go+ Format Test
      run: |
        gop fmt -t ./...